### ISSUE TITLE
Password reset form missing "Confirmation" text for input

### ISSUE THREAD

**Issue by lardcanoe** [team-alembic/ash_authentication_phoenix#495]
Both input fields are called "Password"

Additionally, `Password reset with password` wording is a bit odd.

![image](https://github.com/user-attachments/assets/3caa5e04-f80c-489a-ab8d-892e06f47671)

![image](https://github.com/user-attachments/assets/03fbb7eb-6cbd-4f79-bd44-3fc45b7a5446)

**Comment by zachdaniel** [comment]
Fixed in #494

**Comment by sevenseacat** [comment]
The button text isn't fixed still - it defaults to something like `Password reset with #{strategy}`. I'll take a look at that.
